name: Terraform Docs Check

on:
  pull_request:
    branches: [main]

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install terraform-docs
        run: |
          curl -sSLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate terraform-docs and check for changes
        run: |
          for d in $(find modules -maxdepth 3 -type d); do
            if [ -f "$d/main.tf" ]; then
              terraform-docs markdown table "$d" > "$d/README.md"
            fi
          done

          # Check for any diff
          git diff --exit-code || (
            echo "❌ README.md is outdated. Please run 'terraform-docs' locally and commit the updated README.md files."
            exit 1
          )
