name: Terraform Docs Check

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
         working-dir: .
         output-file: README.md
         output-method: inject
         git-push: "true"

      
